language: node_js
sudo: false
node_js:
  - '7.0'
branches:
  only:
  - master
  - develop
notifications:
  email:
  - kirankumar.amruthaluri@gmail.com
env:
  global:
  - BUILD_DEV: true
install:
  - npm install
before_script:
  - npm run lib-lint
  - npm run react-lint
script:
#  - npm run lib-karma
  - npm run lib-test-coverage
  - npm run react-karma
#  - npm run react-test-coverage
after_script:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
  - process.exit()